### ISSUE TITLE
crashes on MacOS 10.13.5

### ISSUE THREAD

**Issue by skitaeff** [Punzo/SlicerAstro#103]
I was unable to try it. Slicer crashes immediately when I select any astronomy module.

**Comment by Punzo** [comment]
Hi @skitaeff, thanks for reporting. I just tested on 10.13.4 and the binaries worked. I'll update to 10.13.5 and let you know.

**Comment by Punzo** [comment]
I tested on 10.13.5 and works as well. I noticed that the binaries have been built just one hour ago (http://slicer.cdash.org/buildSummary.php?buildid=1298558). It may be possible that something  went wrong in your download (maybe you were very unlucky and the building was finishing just in that moment and SlicerAstro was not completely ready even if it was showing in the extension manager).  May you please uninstall and reinstall SlicerAstro from 3DSlicer (you can do it from the extension manager)?

**Comment by skitaeff** [comment]
I’ve downloaded 4.9.0, and it seem to work ok. I was trying to use “stable” 4.8.1 before. Thanks!
________________________________

Dr Slava Kitaeff
SKA Regional Centre Project Engineer
ERIDANUS National Project Lead

International Centre for Radio Astronomy Research
The University of Western Australia

Astronomy and Space Science
CSIRO

Email: slava.kitaeff@icrar.org<mailto:slava.kitaeff@icrar.org> or slava.kitaeff@csiro.au<mailto:slava.kitaeff@csiro.au>
Tel.: (+61) (0) 8 6488 7744 (ICRAR) or (+61) (0) 8 6436 8865 (CSIRO)
Mob.: +61 404 297 414

Mailing addresses:
M468, University of Western Australia, 35 Stirling Highway, Crawley WA 6009, Australia, or
CSIRO Astronomy and Space Science, PO Box 1130, Bentley WA 6102, Australia

On 19 Jun 2018, at 6:55 pm, Davide Punzo <notifications@github.com<mailto:notifications@github.com>> wrote:


I tested on 10.13.5 and works as well. I noticed that the binaries have been built just one hour ago (http://slicer.cdash.org/buildSummary.php?buildid=1298558). It may be possible that something went wrong in your download (maybe you were very unlucky and the building was finishing just in that moment and SlicerAstro was not completely ready even if it was showing in the extension manager). May you please uninstall and reinstall SlicerAstro from 3DSlicer (you can do it from the extension manager)?

**Comment by Punzo** [comment]
ok perfect! maybe I should have stressed that better. Soon I'll make custom 3DSlicer binaries with SliceAstro already in the package so these issues will not occur.
