### ISSUE TITLE
Update to last version of 3DSlicer

### ISSUE THREAD

**Issue by Punzo** [Punzo/SlicerAstro#106]
Here a list of bugs to fix (and enhancement) to update SlicerAstro to the current version of 3DSlicer (https://github.com/Slicer/Slicer/commit/55fc1d77b0e86e532c0a0f70a4bb75e4c7eb5856 ; 26/11/2019):

High priority:
* [x]  (1) Fix packing of astropy and scipy
* [x]  (2) Fix Contours (in binary segmentation) in the modules AstroVolume, AstroSmoothing and AstroModeling.
* [x]  (3) AstroModeling linking between plots and points annotations is broken.
* [x]  (4) AstroMasking crash when doing a Crop operation on a Region of Interest.
* [x]  (5) AstroStatistics crash when calculating the median.
* [x]  (6) Replace old wigets with new annotation widgets: Ruler with the new line widget in the AstroPVSlice module.

Low priority:
* [x]  (7) Consider updating cfitio from 3.450 to 3.470.
* [x]  (8) Consider updating wcslib from 5.18 to 7.1.
* [ ]  (9) Fix compilation of wcslib for windows for having SlicerAstro binaries for windows too.
* [ ]  (10) Consider updating BBarolo from 1.4 to 1.5.

**Comment by Punzo** [comment]
@vdhulst if you have more please add in this issue.

I'll address this issue during the [3DSlicer project week](https://projectweek.na-mic.org/PW33_2020_GranCanaria/) (20-24 January)

**Comment by vdhulst** [comment]
Downloaded Slicer version 4.11.0-2019-11-28 r28658 and run it under MacOS 10.13.6

Upon startup the following error message appears:
``(base) JMs-MacBook-Pro:apersched vdhulst$ When loading module  "CropVolume" , the dependency "ResampleScalarVectorDWIVolume" failed to be loaded.
Switch to module:  "AstroVolume"``

In the Astro Volume module: changing the transfer function of the 2D display using the cursor within the 2D display window does not work anymore. The slide bars in the menu do work.

**Comment by Punzo** [comment]
> Upon startup the following error message appears:
> `(base) JMs-MacBook-Pro:apersched vdhulst$ When loading module "CropVolume" , the dependency "ResampleScalarVectorDWIVolume" failed to be loaded. Switch to module: "AstroVolume"`

if you use only the modules as listed in https://github.com/Punzo/SlicerAstro/wiki/Get-SlicerAstro#get-slicerastro-from-the-3dslicer-website, that error will not show up. We do not use the CropVolume, which depends on a CLI module (ResampleScalarVectorDWIVolume is a CLI module) and these last you probably have already disabled.

> In the Astro Volume module: changing the transfer function of the 2D display using the cursor within the 2D display window does not work anymore. The slide bars in the menu do work.

that's acutally a new feature, now there are interactive widgets (points, lines, closed curves etc...) which interact with left click. Therefore, for avoiding miss clicks, now you need to activate the 2d color function change with left click and drag on 2D views by clicking on the mouse pointer in the main controller bar (nearby the widgets controller, see image below).

![image](https://user-images.githubusercontent.com/7985338/69902196-d8af4080-138a-11ea-880d-858cdf66016c.png)

**Comment by Punzo** [comment]
@vdhulst  the commit https://github.com/Punzo/SlicerAstro/commit/42c0799c04fbe10b3696915ed89be2ff3baad70f uses the new widget that I and @lassoan developed last year in the PVSlice module. The new line widget shows much better perfomance; and now (in addition to the single left click and drag) with middle click and drag it allows to shift the full widget (I'll update the module wiki as well).

**Comment by Punzo** [comment]
@vdhulst last two points (wcslib for windows and update 3DBarolo to 1.5) will be left for later. I'll close this issue (and open two for teh remaining points). If you will experience bugs related to the recent commits, please open new tickets.
