### ISSUE TITLE
Remove dependency on deprecated Slicer core modules

### ISSUE THREAD

**Issue by lassoan** [Punzo/SlicerAstro#109]
We are planning to remove Slicer core modules that have been superseded by other modules.
https://discourse.slicer.org/t/removing-legacy-modules-in-slicer5/11371

We have noticed that this extension currently uses legacy charts infrastructure (Plots, and Tables modules).

If you want your extension to be available for the upcoming Slicer5 release, please remove dependency to deprecated modules. If you have any questions or need any help with the upgrade, you can write here or post to the Slicer forum. Thank you for your contribution.

**Comment by Punzo** [comment]
Hi Andras, SlicerAstro uses the plot infrastructure (not the chart) that we developed from the beginning. Thanks. I'll close this.

**Comment by lassoan** [comment]
There are still references to DoubleArray node: https://github.com/Punzo/SlicerAstro/search?q=vtkmrmldoublearraynode&unscoped_q=vtkmrmldoublearraynode

If you don't really use them then you can just delete those includes.

**Comment by Punzo** [comment]
ah yes, I think that at a certain point I got rid of them and used simple vtkDoubleArray. Thanks for pointing out! I'll remove the includes.

**Comment by Punzo** [comment]
done in https://github.com/Punzo/SlicerAstro/commit/90e8ad7c08092804b6e6fc302c036985b6a11d7e  and https://github.com/Punzo/SlicerAstro/commit/05bd61b9578b87a4e65ad50d6ac571f20eb6f212 . In the next days I'll check out on the Slicer dahsboard for any other eventual issue. Thanks!
