### ISSUE TITLE
Logo update

### ISSUE THREAD

**Issue by Punzo** [Punzo/SlicerAstro#110]
3DSlicer logo will be soon updated for a modern style: https://discourse.slicer.org/t/proposed-new-slicer-logo/11295/75

Here link for the SlicerAstro one
https://discourse.slicer.org/t/proposed-new-slicerastro-logo/12601

Feedback is welcome. @vdhulst having your input will be great!

**Comment by vdhulst** [comment]
@Punzo I like the new SlicerAstro logo, though am still thinking about the colour of the ring. The current yellow is a bit too dominant and the silver one too inconspicuous. Would be nice to find something in between. I may try a few things in the next few days.

**Comment by Punzo** [comment]
Hi Thijs, I'll try few combination as well and poste them on discourse

**Comment by Punzo** [comment]
@vdhulst I have updated discourse with some options: https://discourse.slicer.org/t/proposed-new-slicerastro-logo/12601/12?u=davide_punzo

[SlicerAstroIcon.zip](https://github.com/Punzo/SlicerAstro/files/4943553/SlicerAstroIcon.zip) here the gimp file for the yellow one if you'd like to play with it

**Comment by vdhulst** [comment]
I tried two more, a light blue and a light green one. I like the light blue one best (colour of the sky). I uploaded pictures and the Gimp files.
![SlicerAstroIcon-1](https://user-images.githubusercontent.com/7922633/87877342-11655e00-c9de-11ea-9342-fe965a68a025.png)
![SlicerAstroIcon-2](https://user-images.githubusercontent.com/7922633/87877350-1e824d00-c9de-11ea-96e8-d100b37784a0.png)
[SlicerAstroIcon-1.xcf.zip](https://github.com/Punzo/SlicerAstro/files/4943843/SlicerAstroIcon-1.xcf.zip)
[SlicerAstroIcon-2.xcf.zip](https://github.com/Punzo/SlicerAstro/files/4943845/SlicerAstroIcon-2.xcf.zip)

**Comment by Punzo** [comment]
thanks, I also like your light blue, I'll update the discourse post

**Comment by Punzo** [comment]
done. See also https://discourse.slicer.org/t/proposed-new-slicerastro-logo/12601/14
