### ISSUE TITLE
CloudLasso selection not working inside the datacube extents

### ISSUE THREAD

**Issue by Fil8** [Punzo/SlicerAstro#30]
When the 3D rendering is zoomed inside the extent of the datacube (pink frame) the cloud lasso selection tool does not work.

**Comment by Punzo** [comment]
Confirmed

**Comment by Punzo** [comment]
fixed in 5f3398fb3b6d95334d3510e2bba4c2840b6b5d21 . @Fil8 please download the new version (tomorrow 02/05/2017) and test it.
