### ISSUE TITLE
ENH: adding astropy in 3DSlicer or SlicerAstro binaries

### ISSUE THREAD

**Issue by Punzo** [Punzo/SlicerAstro#37]

**Comment by Punzo** [comment]
@jcfr

**Comment by Punzo** [comment]
https://discourse.slicer.org/t/slicer-python-packages-use-and-install/984/2

**Comment by jcfr** [comment]
Hi Davide, 

Look like I missed your original comment. Glad you stumbled upon my post on the Slicer forum.

Here are examples of external project allowing to bundle a python package within your extension:
* https://github.com/Radiomics/SlicerRadiomics/tree/master/SuperBuild
* https://github.com/KitwareMedical/SlicerITKPython/blob/master/SuperBuild/External_python-itk.cmake

Note we are still working on these, and will soon add a CMake macro or function to the Slicer build system that will streamline the process.

**Comment by Punzo** [comment]
Hi Jc, oh good thanks a lot for the info! I'll try it at my return from the vacation. It will be nice to have a CMake macro.

**Comment by Punzo** [comment]
For the moment, the installation of astropy in SlicerAstro it is left up to the user as described here:
https://github.com/Punzo/SlicerAstro/wiki/Python-interactor#install-additional-python-packages
