### ISSUE TITLE
BUG+COMP: Python wrapping of MRML nodes does not work with VTK8 build

### ISSUE THREAD

**Issue by Punzo** [Punzo/SlicerAstro#50]

**Comment by Punzo** [comment]
Hi @jcfr, I just tested SlicerAstro againt VTK8 and the wrapping of the MRML classes from extensions seems not working. 

If I compile the current Slicer master with VTK7, the Python wrapping of MRML classes of SlicerAstro works properly. This is my CMakeLists for the MRML:
https://github.com/Punzo/SlicerAstro/blob/master/AstroVolume/MRML/CMakeLists.txt

Can you tell me if it is a bug in Slicer VTK8 build or in my CMake?

Thanks!

**Comment by Punzo** [comment]
Hi @lassoan @pinter,  have you tried to compile and test SlicerRt with Qt5 and VTK8? I am curious if the Python wrapping for MRML classes works for you.

**Comment by lassoan** [comment]
I haven't tried to build any extension with VTK8 yet.

**Comment by Punzo** [comment]
ok, thanks for letting me know

**Comment by Punzo** [comment]
Hi @jcfr @lassoan I compiled SlicerIGT with VTK8 and the MRML classes are not visible from the python console as well. It seems the issue is there for all the extensions, so I'll move this issue from here to Mantis.

**Comment by jcfr** [comment]
Thanks for testing this.

xref https://issues.slicer.org/view.php?id=4448
