### ISSUE TITLE
COMP: linux binaries require flex to be compiled

### ISSUE THREAD

**Issue by Punzo** [Punzo/SlicerAstro#91]
linux Qt5.10 build kitware machine error (http://slicer.cdash.org/buildSummary.php?buildid=1230850) (during compilation of wcslib): 
configure: WARNING: Flex version 2.5.9 or later does not appear to be  available

solution 1:
1) @jcfr may you install flex to the linux factory machine;
2) (not desirable) add pre-generated sources.

**Comment by jcfr** [comment]
Hi Davide,

Could you update the docker image we use ? See
https://github.com/Slicer/SlicerBuildEnvironment/tree/master/Docker/qt5-centos7

Jc

**Comment by Punzo** [comment]
Hi Jc, ok I'll have a look in the next week. Thanks!

**Comment by Punzo** [comment]
pull request at https://github.com/Slicer/SlicerBuildEnvironment/pull/2

**Comment by Punzo** [comment]
done in https://github.com/Slicer/SlicerBuildEnvironment/commit/9d25521e37ae67e72f660040457fe43a1b011eb4
